# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1175, 614)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_design = QtWidgets.QWidget(Dialog)
        self.widget_design.setStyleSheet("\n"
"   QWidget{\n"
"    background-color: rgb(33, 37, 43);\n"
"    color: rgb(208, 208, 208);\n"
"    font-size: 10pt;\n"
"}\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ScrollBars */\n"
" QScrollBar {\n"
"border: none;                                                /* без границ */\n"
"    border-right:5px solid rgb(211, 211, 211);;    /* С правой красной раницей */\n"
" }\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 8px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/* Ползунок */\n"
" QScrollBar::handle:vertical {    \n"
"    background:rgb(255, 255, 255);\n"
"    min-height: 25px;\n"
"    border-radius: 4px\n"
" }\n"
"/*Нижняя стрелка*/\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"/*Верхняя стрелка*/\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"/* Цвета нижних и верхних стрелок */\n"
" QScrollBar::up-arrow:vertical{\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"     background: rgb(255, 255, 255);\n"
" }\n"
"QScrollBar::down-arrow:vertical{\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"     background: rgb(255, 255, 255);\n"
"}\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"/* ///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"RadioButton */\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(255, 255, 255);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"/* срабатывает, когда пользователь наводит на элемент мышью */\n"
"QRadioButton:hover {\n"
"    background-color:rgb(40, 44, 52);            /* задаем цвет фона */\n"
"}\n"
"/* срабатывает, при нажатии*/\n"
"QRadioButton:pressed      {\n"
"    background-color:rgb(170, 170, 170);        /* задаем цвет фона */\n"
"    color:  rgb(0, 0, 0);\n"
"    border: none;                                                /* без границ */\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QCheckBox */\n"
"/* Стандартное состояние*/\n"
"QCheckBox{\n"
"    padding-left: 8px;        /* Отступ слева */\n"
"    padding-right: -8px;    /* Отступ справа */\n"
"}\n"
"\n"
"/* Состояние - не выбран*/\n"
"QCheckBox::indicator:unchecked {\n"
"    /* Выбор картинки*/\n"
"    image: url(:/checkbox_status_success/resource/checkbox_status_success/check_error_red_24dp.svg)\n"
"}\n"
"\n"
"/* Состояние -  выбран*/\n"
"QCheckBox::indicator:checked {\n"
"    /* Выбор картинки*/\n"
"    image: url(:/checkbox_status_success/resource/checkbox_status_success/check_ok_grean_24dp.svg);\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QPushButton */\n"
"/*Стандартное состояние для кнопки*/\n"
"QPushButton {\n"
"    font-size: 12pt;\n"
"    background-color:rgb(37, 41, 48);/* задает цвет фона */\n"
"    display: inline-block;                            /* пределяет, будет ли элемент обрабатываться как блочный или встроенный элемент */\n"
"    border: 1px solid rgb(52, 59, 72);        /* задает границу элемента */\n"
"\n"
"    /* задает иконку */\n"
"    background-position: left center;                            /* выравнивание иконки */\n"
"    background-repeat: no-repeat;                                /* повторять иконку */\n"
"} \n"
"\n"
"/* срабатывает, когда пользователь наводит на элемент мышью */\n"
"QPushButton:hover {\n"
"    background-color:rgb(40, 44, 52);            /* задаем цвет фона */\n"
"    border: none;                                                /* без границ */\n"
"    border-left:4px solid rgb(208, 208, 208);    /* С правой красной раницей */\n"
"}\n"
"\n"
"\n"
"/* срабатывает, при нажатии*/\n"
"QPushButton:pressed      {\n"
"    background-color:rgb(170, 170, 170);        /* задаем цвет фона */\n"
"    color: rgb(181, 181, 181);\n"
"    border: none;                                                /* без границ */\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QLineEdit */\n"
"/* Стиль по умолчанию */\n"
"QLineEdit:enabled{\n"
"    background-color:rgb(44, 49, 58); /* Устанавливаем цвет заливки */\n"
"    border: 1px solid rgb(255, 255, 255); \n"
"}\n"
"\n"
"/* Если поле отключено */\n"
"QLineEdit:disabled {\n"
"    background-color:  rgba(67, 74, 88, 0); /* Устанавливаем цвет заливки */\n"
"    border: 1px solid rgb(255, 255, 255); \n"
"    color: rgb(67, 74, 88);\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QGroupBox */\n"
"QGroupBox{\n"
"    color:rgb(255, 255, 255);    /* задает цвет шрифта */\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QTableWidget */\n"
"\n"
"QTableWidget {    \n"
"    gridline-color: rgb(136, 136, 136);\n"
"    border-top: 1px solid rgb(54, 60, 74);\n"
"    border-bottom: 1px solid  rgb(54, 60, 74);\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: rgb(72, 81, 94);\n"
"}\n"
"QHeaderView { qproperty-defaultAlignment: AlignCenter; }\n"
"/*Цвет верхнего и левого поля*/\n"
"QHeaderView::section{\n"
"    background-color:rgb(37, 41, 48);\n"
"    border-style: none;\n"
"border: 1px solid rgb(136, 136, 136);\n"
"}\n"
"/*Кнопка в верхнем левом углу*/\n"
"QTableCornerButton::section {background-color:rgb(33, 37, 43); }\n"
"\n"
"QWidget#widget_loading_data {\n"
"    border-bottom: 2px solid rgb(208, 208, 208);\n"
"}\n"
"QWidget#widget_processing {\n"
"    border-top: 2px solid rgb(208, 208, 208);\n"
"}\n"
"QScrollArea{\n"
"border: none;\n"
"}")
        self.widget_design.setObjectName("widget_design")
        self.layout_design = QtWidgets.QHBoxLayout(self.widget_design)
        self.layout_design.setContentsMargins(0, 0, 0, 0)
        self.layout_design.setSpacing(3)
        self.layout_design.setObjectName("layout_design")
        self.widget_menu = QtWidgets.QWidget(self.widget_design)
        self.widget_menu.setMinimumSize(QtCore.QSize(200, 0))
        self.widget_menu.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget_menu.setObjectName("widget_menu")
        self.layout_menu = QtWidgets.QVBoxLayout(self.widget_menu)
        self.layout_menu.setContentsMargins(0, 0, 0, 6)
        self.layout_menu.setSpacing(6)
        self.layout_menu.setObjectName("layout_menu")
        self.scrollArea = QtWidgets.QScrollArea(self.widget_menu)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -517, 192, 1037))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, -1, 3, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_loading_data = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_loading_data.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_loading_data.setCheckable(True)
        self.pushButton_loading_data.setChecked(True)
        self.pushButton_loading_data.setObjectName("pushButton_loading_data")
        self.verticalLayout_2.addWidget(self.pushButton_loading_data)
        self.widget_loading_data = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_loading_data.setStyleSheet("")
        self.widget_loading_data.setObjectName("widget_loading_data")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_loading_data)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 6)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_choice_dome_or_picture = QtWidgets.QGroupBox(self.widget_loading_data)
        self.groupBox_choice_dome_or_picture.setObjectName("groupBox_choice_dome_or_picture")
        self.layout_choice_dome_or_picture = QtWidgets.QVBoxLayout(self.groupBox_choice_dome_or_picture)
        self.layout_choice_dome_or_picture.setContentsMargins(6, 0, 0, 5)
        self.layout_choice_dome_or_picture.setSpacing(0)
        self.layout_choice_dome_or_picture.setObjectName("layout_choice_dome_or_picture")
        self.radioButton_generation_domes = QtWidgets.QRadioButton(self.groupBox_choice_dome_or_picture)
        self.radioButton_generation_domes.setChecked(True)
        self.radioButton_generation_domes.setAutoRepeat(False)
        self.radioButton_generation_domes.setAutoExclusive(True)
        self.radioButton_generation_domes.setObjectName("radioButton_generation_domes")
        self.layout_choice_dome_or_picture.addWidget(self.radioButton_generation_domes)
        self.radioButton_loading_pictures = QtWidgets.QRadioButton(self.groupBox_choice_dome_or_picture)
        self.radioButton_loading_pictures.setAutoRepeat(False)
        self.radioButton_loading_pictures.setAutoExclusive(True)
        self.radioButton_loading_pictures.setObjectName("radioButton_loading_pictures")
        self.layout_choice_dome_or_picture.addWidget(self.radioButton_loading_pictures)
        self.verticalLayout_3.addWidget(self.groupBox_choice_dome_or_picture)
        self.widget_dome_parameters = QtWidgets.QWidget(self.widget_loading_data)
        self.widget_dome_parameters.setObjectName("widget_dome_parameters")
        self.layout_dome_parameters = QtWidgets.QVBoxLayout(self.widget_dome_parameters)
        self.layout_dome_parameters.setContentsMargins(0, -1, 0, 5)
        self.layout_dome_parameters.setObjectName("layout_dome_parameters")
        self.groupBox_area_size = QtWidgets.QGroupBox(self.widget_dome_parameters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_area_size.sizePolicy().hasHeightForWidth())
        self.groupBox_area_size.setSizePolicy(sizePolicy)
        self.groupBox_area_size.setObjectName("groupBox_area_size")
        self.layout_area_size = QtWidgets.QVBoxLayout(self.groupBox_area_size)
        self.layout_area_size.setContentsMargins(0, 0, 0, 9)
        self.layout_area_size.setSpacing(5)
        self.layout_area_size.setObjectName("layout_area_size")
        self.widget_width_area = QtWidgets.QWidget(self.groupBox_area_size)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_width_area.sizePolicy().hasHeightForWidth())
        self.widget_width_area.setSizePolicy(sizePolicy)
        self.widget_width_area.setObjectName("widget_width_area")
        self.layout_width_area = QtWidgets.QHBoxLayout(self.widget_width_area)
        self.layout_width_area.setContentsMargins(-1, 0, -1, 0)
        self.layout_width_area.setObjectName("layout_width_area")
        self.label_text_width_area = QtWidgets.QLabel(self.widget_width_area)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_text_width_area.setFont(font)
        self.label_text_width_area.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_width_area.setObjectName("label_text_width_area")
        self.layout_width_area.addWidget(self.label_text_width_area)
        self.lineEdit_width_area = QtWidgets.QLineEdit(self.widget_width_area)
        self.lineEdit_width_area.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_width_area.setObjectName("lineEdit_width_area")
        self.layout_width_area.addWidget(self.lineEdit_width_area)
        self.layout_width_area.setStretch(0, 1)
        self.layout_width_area.setStretch(1, 1)
        self.layout_area_size.addWidget(self.widget_width_area)
        self.widget_height_area = QtWidgets.QWidget(self.groupBox_area_size)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_height_area.sizePolicy().hasHeightForWidth())
        self.widget_height_area.setSizePolicy(sizePolicy)
        self.widget_height_area.setObjectName("widget_height_area")
        self.layout_height_area = QtWidgets.QHBoxLayout(self.widget_height_area)
        self.layout_height_area.setContentsMargins(-1, 0, 9, 0)
        self.layout_height_area.setObjectName("layout_height_area")
        self.label_text_height_area = QtWidgets.QLabel(self.widget_height_area)
        self.label_text_height_area.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_height_area.setObjectName("label_text_height_area")
        self.layout_height_area.addWidget(self.label_text_height_area)
        self.lineEdit_height_area = QtWidgets.QLineEdit(self.widget_height_area)
        self.lineEdit_height_area.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_height_area.setObjectName("lineEdit_height_area")
        self.layout_height_area.addWidget(self.lineEdit_height_area)
        self.layout_height_area.setStretch(0, 1)
        self.layout_height_area.setStretch(1, 1)
        self.layout_area_size.addWidget(self.widget_height_area)
        self.layout_dome_parameters.addWidget(self.groupBox_area_size)
        self.groupBox_dome_1 = QtWidgets.QGroupBox(self.widget_dome_parameters)
        self.groupBox_dome_1.setObjectName("groupBox_dome_1")
        self.layout_dome_1 = QtWidgets.QVBoxLayout(self.groupBox_dome_1)
        self.layout_dome_1.setContentsMargins(0, 0, 0, 9)
        self.layout_dome_1.setSpacing(5)
        self.layout_dome_1.setObjectName("layout_dome_1")
        self.widget_amplitude_1 = QtWidgets.QWidget(self.groupBox_dome_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_amplitude_1.sizePolicy().hasHeightForWidth())
        self.widget_amplitude_1.setSizePolicy(sizePolicy)
        self.widget_amplitude_1.setObjectName("widget_amplitude_1")
        self.layout_amplitude_1 = QtWidgets.QHBoxLayout(self.widget_amplitude_1)
        self.layout_amplitude_1.setContentsMargins(-1, 0, -1, 0)
        self.layout_amplitude_1.setObjectName("layout_amplitude_1")
        self.label_text_amplitude_1 = QtWidgets.QLabel(self.widget_amplitude_1)
        self.label_text_amplitude_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_amplitude_1.setObjectName("label_text_amplitude_1")
        self.layout_amplitude_1.addWidget(self.label_text_amplitude_1)
        self.lineEdit_amplitude_1 = QtWidgets.QLineEdit(self.widget_amplitude_1)
        self.lineEdit_amplitude_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_amplitude_1.setObjectName("lineEdit_amplitude_1")
        self.layout_amplitude_1.addWidget(self.lineEdit_amplitude_1)
        self.layout_amplitude_1.setStretch(0, 1)
        self.layout_amplitude_1.setStretch(1, 1)
        self.layout_dome_1.addWidget(self.widget_amplitude_1)
        self.widget_x0_1 = QtWidgets.QWidget(self.groupBox_dome_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_x0_1.sizePolicy().hasHeightForWidth())
        self.widget_x0_1.setSizePolicy(sizePolicy)
        self.widget_x0_1.setObjectName("widget_x0_1")
        self.layout_x0_1 = QtWidgets.QHBoxLayout(self.widget_x0_1)
        self.layout_x0_1.setContentsMargins(-1, 0, -1, 0)
        self.layout_x0_1.setObjectName("layout_x0_1")
        self.label_text_x0_1 = QtWidgets.QLabel(self.widget_x0_1)
        self.label_text_x0_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_x0_1.setObjectName("label_text_x0_1")
        self.layout_x0_1.addWidget(self.label_text_x0_1)
        self.lineEdit_x0_1 = QtWidgets.QLineEdit(self.widget_x0_1)
        self.lineEdit_x0_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_x0_1.setObjectName("lineEdit_x0_1")
        self.layout_x0_1.addWidget(self.lineEdit_x0_1)
        self.layout_x0_1.setStretch(0, 1)
        self.layout_x0_1.setStretch(1, 1)
        self.layout_dome_1.addWidget(self.widget_x0_1)
        self.widget_sigma_x_1 = QtWidgets.QWidget(self.groupBox_dome_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_sigma_x_1.sizePolicy().hasHeightForWidth())
        self.widget_sigma_x_1.setSizePolicy(sizePolicy)
        self.widget_sigma_x_1.setObjectName("widget_sigma_x_1")
        self.layout_sigma_x_1 = QtWidgets.QHBoxLayout(self.widget_sigma_x_1)
        self.layout_sigma_x_1.setContentsMargins(-1, 0, -1, 0)
        self.layout_sigma_x_1.setObjectName("layout_sigma_x_1")
        self.label_text_sigma_x_1 = QtWidgets.QLabel(self.widget_sigma_x_1)
        self.label_text_sigma_x_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_sigma_x_1.setObjectName("label_text_sigma_x_1")
        self.layout_sigma_x_1.addWidget(self.label_text_sigma_x_1)
        self.lineEdit_sigma_x_1 = QtWidgets.QLineEdit(self.widget_sigma_x_1)
        self.lineEdit_sigma_x_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_sigma_x_1.setObjectName("lineEdit_sigma_x_1")
        self.layout_sigma_x_1.addWidget(self.lineEdit_sigma_x_1)
        self.layout_sigma_x_1.setStretch(0, 1)
        self.layout_sigma_x_1.setStretch(1, 1)
        self.layout_dome_1.addWidget(self.widget_sigma_x_1)
        self.widget_y0_1 = QtWidgets.QWidget(self.groupBox_dome_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_y0_1.sizePolicy().hasHeightForWidth())
        self.widget_y0_1.setSizePolicy(sizePolicy)
        self.widget_y0_1.setObjectName("widget_y0_1")
        self.layout_y0_1 = QtWidgets.QHBoxLayout(self.widget_y0_1)
        self.layout_y0_1.setContentsMargins(-1, 0, -1, 0)
        self.layout_y0_1.setObjectName("layout_y0_1")
        self.label_text_y0_1 = QtWidgets.QLabel(self.widget_y0_1)
        self.label_text_y0_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_y0_1.setObjectName("label_text_y0_1")
        self.layout_y0_1.addWidget(self.label_text_y0_1)
        self.lineEdit_y0_1 = QtWidgets.QLineEdit(self.widget_y0_1)
        self.lineEdit_y0_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_y0_1.setObjectName("lineEdit_y0_1")
        self.layout_y0_1.addWidget(self.lineEdit_y0_1)
        self.layout_y0_1.setStretch(0, 1)
        self.layout_y0_1.setStretch(1, 1)
        self.layout_dome_1.addWidget(self.widget_y0_1)
        self.widget_sigma_y_1 = QtWidgets.QWidget(self.groupBox_dome_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_sigma_y_1.sizePolicy().hasHeightForWidth())
        self.widget_sigma_y_1.setSizePolicy(sizePolicy)
        self.widget_sigma_y_1.setObjectName("widget_sigma_y_1")
        self.layout_sigma_y_1 = QtWidgets.QHBoxLayout(self.widget_sigma_y_1)
        self.layout_sigma_y_1.setContentsMargins(-1, 0, -1, 0)
        self.layout_sigma_y_1.setObjectName("layout_sigma_y_1")
        self.label_text_sigma_y_1 = QtWidgets.QLabel(self.widget_sigma_y_1)
        self.label_text_sigma_y_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_sigma_y_1.setObjectName("label_text_sigma_y_1")
        self.layout_sigma_y_1.addWidget(self.label_text_sigma_y_1)
        self.lineEdit_sigma_y_1 = QtWidgets.QLineEdit(self.widget_sigma_y_1)
        self.lineEdit_sigma_y_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_sigma_y_1.setObjectName("lineEdit_sigma_y_1")
        self.layout_sigma_y_1.addWidget(self.lineEdit_sigma_y_1)
        self.layout_sigma_y_1.setStretch(0, 1)
        self.layout_sigma_y_1.setStretch(1, 1)
        self.layout_dome_1.addWidget(self.widget_sigma_y_1)
        self.layout_dome_parameters.addWidget(self.groupBox_dome_1)
        self.groupBox_dome_2 = QtWidgets.QGroupBox(self.widget_dome_parameters)
        self.groupBox_dome_2.setObjectName("groupBox_dome_2")
        self.layout_dome_2 = QtWidgets.QVBoxLayout(self.groupBox_dome_2)
        self.layout_dome_2.setContentsMargins(0, 0, 0, 9)
        self.layout_dome_2.setSpacing(5)
        self.layout_dome_2.setObjectName("layout_dome_2")
        self.widget_amplitude_2 = QtWidgets.QWidget(self.groupBox_dome_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_amplitude_2.sizePolicy().hasHeightForWidth())
        self.widget_amplitude_2.setSizePolicy(sizePolicy)
        self.widget_amplitude_2.setObjectName("widget_amplitude_2")
        self.layout_amplitude_2 = QtWidgets.QHBoxLayout(self.widget_amplitude_2)
        self.layout_amplitude_2.setContentsMargins(-1, 0, -1, 0)
        self.layout_amplitude_2.setObjectName("layout_amplitude_2")
        self.label_text_amplitude_2 = QtWidgets.QLabel(self.widget_amplitude_2)
        self.label_text_amplitude_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_amplitude_2.setObjectName("label_text_amplitude_2")
        self.layout_amplitude_2.addWidget(self.label_text_amplitude_2)
        self.lineEdit_amplitude_2 = QtWidgets.QLineEdit(self.widget_amplitude_2)
        self.lineEdit_amplitude_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_amplitude_2.setObjectName("lineEdit_amplitude_2")
        self.layout_amplitude_2.addWidget(self.lineEdit_amplitude_2)
        self.layout_amplitude_2.setStretch(0, 1)
        self.layout_amplitude_2.setStretch(1, 1)
        self.layout_dome_2.addWidget(self.widget_amplitude_2)
        self.widget_x0_2 = QtWidgets.QWidget(self.groupBox_dome_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_x0_2.sizePolicy().hasHeightForWidth())
        self.widget_x0_2.setSizePolicy(sizePolicy)
        self.widget_x0_2.setObjectName("widget_x0_2")
        self.layout_x0_2 = QtWidgets.QHBoxLayout(self.widget_x0_2)
        self.layout_x0_2.setContentsMargins(-1, 0, -1, 0)
        self.layout_x0_2.setObjectName("layout_x0_2")
        self.label_text_x0_2 = QtWidgets.QLabel(self.widget_x0_2)
        self.label_text_x0_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_x0_2.setObjectName("label_text_x0_2")
        self.layout_x0_2.addWidget(self.label_text_x0_2)
        self.lineEdit_x0_2 = QtWidgets.QLineEdit(self.widget_x0_2)
        self.lineEdit_x0_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_x0_2.setObjectName("lineEdit_x0_2")
        self.layout_x0_2.addWidget(self.lineEdit_x0_2)
        self.layout_x0_2.setStretch(0, 1)
        self.layout_x0_2.setStretch(1, 1)
        self.layout_dome_2.addWidget(self.widget_x0_2)
        self.widget_sigma_x_2 = QtWidgets.QWidget(self.groupBox_dome_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_sigma_x_2.sizePolicy().hasHeightForWidth())
        self.widget_sigma_x_2.setSizePolicy(sizePolicy)
        self.widget_sigma_x_2.setObjectName("widget_sigma_x_2")
        self.layout_sigma_x_2 = QtWidgets.QHBoxLayout(self.widget_sigma_x_2)
        self.layout_sigma_x_2.setContentsMargins(-1, 0, -1, 0)
        self.layout_sigma_x_2.setObjectName("layout_sigma_x_2")
        self.label_text_sigma_x_2 = QtWidgets.QLabel(self.widget_sigma_x_2)
        self.label_text_sigma_x_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_sigma_x_2.setObjectName("label_text_sigma_x_2")
        self.layout_sigma_x_2.addWidget(self.label_text_sigma_x_2)
        self.lineEdit_sigma_x_2 = QtWidgets.QLineEdit(self.widget_sigma_x_2)
        self.lineEdit_sigma_x_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_sigma_x_2.setObjectName("lineEdit_sigma_x_2")
        self.layout_sigma_x_2.addWidget(self.lineEdit_sigma_x_2)
        self.layout_sigma_x_2.setStretch(0, 1)
        self.layout_sigma_x_2.setStretch(1, 1)
        self.layout_dome_2.addWidget(self.widget_sigma_x_2)
        self.widget_y0_2 = QtWidgets.QWidget(self.groupBox_dome_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_y0_2.sizePolicy().hasHeightForWidth())
        self.widget_y0_2.setSizePolicy(sizePolicy)
        self.widget_y0_2.setObjectName("widget_y0_2")
        self.layout_y0_2 = QtWidgets.QHBoxLayout(self.widget_y0_2)
        self.layout_y0_2.setContentsMargins(-1, 0, -1, 0)
        self.layout_y0_2.setObjectName("layout_y0_2")
        self.label_text_y0_2 = QtWidgets.QLabel(self.widget_y0_2)
        self.label_text_y0_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_y0_2.setObjectName("label_text_y0_2")
        self.layout_y0_2.addWidget(self.label_text_y0_2)
        self.lineEdit_y0_2 = QtWidgets.QLineEdit(self.widget_y0_2)
        self.lineEdit_y0_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_y0_2.setObjectName("lineEdit_y0_2")
        self.layout_y0_2.addWidget(self.lineEdit_y0_2)
        self.layout_y0_2.setStretch(0, 1)
        self.layout_y0_2.setStretch(1, 1)
        self.layout_dome_2.addWidget(self.widget_y0_2)
        self.widget_sigma_y_2 = QtWidgets.QWidget(self.groupBox_dome_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_sigma_y_2.sizePolicy().hasHeightForWidth())
        self.widget_sigma_y_2.setSizePolicy(sizePolicy)
        self.widget_sigma_y_2.setObjectName("widget_sigma_y_2")
        self.layout_sigma_y_2 = QtWidgets.QHBoxLayout(self.widget_sigma_y_2)
        self.layout_sigma_y_2.setContentsMargins(-1, 0, -1, 0)
        self.layout_sigma_y_2.setObjectName("layout_sigma_y_2")
        self.label_text_sigma_y_2 = QtWidgets.QLabel(self.widget_sigma_y_2)
        self.label_text_sigma_y_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_sigma_y_2.setObjectName("label_text_sigma_y_2")
        self.layout_sigma_y_2.addWidget(self.label_text_sigma_y_2)
        self.lineEdit_sigma_y_2 = QtWidgets.QLineEdit(self.widget_sigma_y_2)
        self.lineEdit_sigma_y_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_sigma_y_2.setObjectName("lineEdit_sigma_y_2")
        self.layout_sigma_y_2.addWidget(self.lineEdit_sigma_y_2)
        self.layout_sigma_y_2.setStretch(0, 1)
        self.layout_sigma_y_2.setStretch(1, 1)
        self.layout_dome_2.addWidget(self.widget_sigma_y_2)
        self.layout_dome_parameters.addWidget(self.groupBox_dome_2)
        self.groupBox_dome_3 = QtWidgets.QGroupBox(self.widget_dome_parameters)
        self.groupBox_dome_3.setObjectName("groupBox_dome_3")
        self.layout_dome_3 = QtWidgets.QVBoxLayout(self.groupBox_dome_3)
        self.layout_dome_3.setContentsMargins(0, 0, 0, 9)
        self.layout_dome_3.setSpacing(5)
        self.layout_dome_3.setObjectName("layout_dome_3")
        self.widget_amplitude_3 = QtWidgets.QWidget(self.groupBox_dome_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_amplitude_3.sizePolicy().hasHeightForWidth())
        self.widget_amplitude_3.setSizePolicy(sizePolicy)
        self.widget_amplitude_3.setObjectName("widget_amplitude_3")
        self.layout_amplitude_3 = QtWidgets.QHBoxLayout(self.widget_amplitude_3)
        self.layout_amplitude_3.setContentsMargins(-1, 0, -1, 0)
        self.layout_amplitude_3.setObjectName("layout_amplitude_3")
        self.label_text_amplitude_3 = QtWidgets.QLabel(self.widget_amplitude_3)
        self.label_text_amplitude_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_amplitude_3.setObjectName("label_text_amplitude_3")
        self.layout_amplitude_3.addWidget(self.label_text_amplitude_3)
        self.lineEdit_amplitude_3 = QtWidgets.QLineEdit(self.widget_amplitude_3)
        self.lineEdit_amplitude_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_amplitude_3.setObjectName("lineEdit_amplitude_3")
        self.layout_amplitude_3.addWidget(self.lineEdit_amplitude_3)
        self.layout_amplitude_3.setStretch(0, 1)
        self.layout_amplitude_3.setStretch(1, 1)
        self.layout_dome_3.addWidget(self.widget_amplitude_3)
        self.widget_x0_3 = QtWidgets.QWidget(self.groupBox_dome_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_x0_3.sizePolicy().hasHeightForWidth())
        self.widget_x0_3.setSizePolicy(sizePolicy)
        self.widget_x0_3.setObjectName("widget_x0_3")
        self.layout_x0_3 = QtWidgets.QHBoxLayout(self.widget_x0_3)
        self.layout_x0_3.setContentsMargins(-1, 0, -1, 0)
        self.layout_x0_3.setObjectName("layout_x0_3")
        self.label_text_x0_3 = QtWidgets.QLabel(self.widget_x0_3)
        self.label_text_x0_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_x0_3.setObjectName("label_text_x0_3")
        self.layout_x0_3.addWidget(self.label_text_x0_3)
        self.lineEdit_x0_3 = QtWidgets.QLineEdit(self.widget_x0_3)
        self.lineEdit_x0_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_x0_3.setObjectName("lineEdit_x0_3")
        self.layout_x0_3.addWidget(self.lineEdit_x0_3)
        self.layout_x0_3.setStretch(0, 1)
        self.layout_x0_3.setStretch(1, 1)
        self.layout_dome_3.addWidget(self.widget_x0_3)
        self.widget_sigma_x_3 = QtWidgets.QWidget(self.groupBox_dome_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_sigma_x_3.sizePolicy().hasHeightForWidth())
        self.widget_sigma_x_3.setSizePolicy(sizePolicy)
        self.widget_sigma_x_3.setObjectName("widget_sigma_x_3")
        self.layout_sigma_x_3 = QtWidgets.QHBoxLayout(self.widget_sigma_x_3)
        self.layout_sigma_x_3.setContentsMargins(-1, 0, -1, 0)
        self.layout_sigma_x_3.setObjectName("layout_sigma_x_3")
        self.label_text_sigma_x_3 = QtWidgets.QLabel(self.widget_sigma_x_3)
        self.label_text_sigma_x_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_sigma_x_3.setObjectName("label_text_sigma_x_3")
        self.layout_sigma_x_3.addWidget(self.label_text_sigma_x_3)
        self.lineEdit_sigma_x_3 = QtWidgets.QLineEdit(self.widget_sigma_x_3)
        self.lineEdit_sigma_x_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_sigma_x_3.setObjectName("lineEdit_sigma_x_3")
        self.layout_sigma_x_3.addWidget(self.lineEdit_sigma_x_3)
        self.layout_sigma_x_3.setStretch(0, 1)
        self.layout_sigma_x_3.setStretch(1, 1)
        self.layout_dome_3.addWidget(self.widget_sigma_x_3)
        self.widget_y0_3 = QtWidgets.QWidget(self.groupBox_dome_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_y0_3.sizePolicy().hasHeightForWidth())
        self.widget_y0_3.setSizePolicy(sizePolicy)
        self.widget_y0_3.setObjectName("widget_y0_3")
        self.layout_y0_3 = QtWidgets.QHBoxLayout(self.widget_y0_3)
        self.layout_y0_3.setContentsMargins(-1, 0, -1, 0)
        self.layout_y0_3.setObjectName("layout_y0_3")
        self.label_text_y0_3 = QtWidgets.QLabel(self.widget_y0_3)
        self.label_text_y0_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_y0_3.setObjectName("label_text_y0_3")
        self.layout_y0_3.addWidget(self.label_text_y0_3)
        self.lineEdit_y0_3 = QtWidgets.QLineEdit(self.widget_y0_3)
        self.lineEdit_y0_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_y0_3.setObjectName("lineEdit_y0_3")
        self.layout_y0_3.addWidget(self.lineEdit_y0_3)
        self.layout_y0_3.setStretch(0, 1)
        self.layout_y0_3.setStretch(1, 1)
        self.layout_dome_3.addWidget(self.widget_y0_3)
        self.widget_sigma_y_3 = QtWidgets.QWidget(self.groupBox_dome_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_sigma_y_3.sizePolicy().hasHeightForWidth())
        self.widget_sigma_y_3.setSizePolicy(sizePolicy)
        self.widget_sigma_y_3.setObjectName("widget_sigma_y_3")
        self.layout_sigma_y_3 = QtWidgets.QHBoxLayout(self.widget_sigma_y_3)
        self.layout_sigma_y_3.setContentsMargins(-1, 0, -1, 0)
        self.layout_sigma_y_3.setObjectName("layout_sigma_y_3")
        self.label_text_sigma_y_3 = QtWidgets.QLabel(self.widget_sigma_y_3)
        self.label_text_sigma_y_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_sigma_y_3.setObjectName("label_text_sigma_y_3")
        self.layout_sigma_y_3.addWidget(self.label_text_sigma_y_3)
        self.lineEdit_sigma_y_3 = QtWidgets.QLineEdit(self.widget_sigma_y_3)
        self.lineEdit_sigma_y_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_sigma_y_3.setObjectName("lineEdit_sigma_y_3")
        self.layout_sigma_y_3.addWidget(self.lineEdit_sigma_y_3)
        self.layout_sigma_y_3.setStretch(0, 1)
        self.layout_sigma_y_3.setStretch(1, 1)
        self.layout_dome_3.addWidget(self.widget_sigma_y_3)
        self.layout_dome_parameters.addWidget(self.groupBox_dome_3)
        self.pushButton_display_domes = QtWidgets.QPushButton(self.widget_dome_parameters)
        self.pushButton_display_domes.setFlat(False)
        self.pushButton_display_domes.setObjectName("pushButton_display_domes")
        self.layout_dome_parameters.addWidget(self.pushButton_display_domes)
        self.verticalLayout_3.addWidget(self.widget_dome_parameters)
        self.widget_loading_pictures = QtWidgets.QWidget(self.widget_loading_data)
        self.widget_loading_pictures.setEnabled(False)
        self.widget_loading_pictures.setStyleSheet("")
        self.widget_loading_pictures.setObjectName("widget_loading_pictures")
        self.layout_loading_pictures = QtWidgets.QVBoxLayout(self.widget_loading_pictures)
        self.layout_loading_pictures.setContentsMargins(0, 0, 0, 5)
        self.layout_loading_pictures.setSpacing(0)
        self.layout_loading_pictures.setObjectName("layout_loading_pictures")
        self.widget_path_to_picture = QtWidgets.QWidget(self.widget_loading_pictures)
        self.widget_path_to_picture.setObjectName("widget_path_to_picture")
        self.layout_path_to_picture = QtWidgets.QHBoxLayout(self.widget_path_to_picture)
        self.layout_path_to_picture.setContentsMargins(9, 0, 9, 2)
        self.layout_path_to_picture.setObjectName("layout_path_to_picture")
        self.label_text_loading_pictures = QtWidgets.QLabel(self.widget_path_to_picture)
        self.label_text_loading_pictures.setObjectName("label_text_loading_pictures")
        self.layout_path_to_picture.addWidget(self.label_text_loading_pictures)
        self.pushButton_loading_pictures = QtWidgets.QPushButton(self.widget_path_to_picture)
        self.pushButton_loading_pictures.setMinimumSize(QtCore.QSize(35, 30))
        self.pushButton_loading_pictures.setMaximumSize(QtCore.QSize(35, 30))
        self.pushButton_loading_pictures.setStyleSheet("/* срабатывает, когда пользователь наводит на элемент мышью */\n"
"QPushButton:hover {\n"
"    border: none;                                                /* без границ */\n"
"}")
        self.pushButton_loading_pictures.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/menu/resource/file_download_white_24dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_loading_pictures.setIcon(icon)
        self.pushButton_loading_pictures.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_loading_pictures.setObjectName("pushButton_loading_pictures")
        self.layout_path_to_picture.addWidget(self.pushButton_loading_pictures)
        self.layout_loading_pictures.addWidget(self.widget_path_to_picture)
        self.groupBox_picture_type = QtWidgets.QGroupBox(self.widget_loading_pictures)
        self.groupBox_picture_type.setObjectName("groupBox_picture_type")
        self.layout_picture_type = QtWidgets.QHBoxLayout(self.groupBox_picture_type)
        self.layout_picture_type.setContentsMargins(9, 5, 0, 5)
        self.layout_picture_type.setObjectName("layout_picture_type")
        self.radioButton_color_picture = QtWidgets.QRadioButton(self.groupBox_picture_type)
        self.radioButton_color_picture.setChecked(True)
        self.radioButton_color_picture.setObjectName("radioButton_color_picture")
        self.layout_picture_type.addWidget(self.radioButton_color_picture)
        self.radioButton_gray_picture = QtWidgets.QRadioButton(self.groupBox_picture_type)
        self.radioButton_gray_picture.setObjectName("radioButton_gray_picture")
        self.layout_picture_type.addWidget(self.radioButton_gray_picture)
        self.layout_loading_pictures.addWidget(self.groupBox_picture_type)
        self.verticalLayout_3.addWidget(self.widget_loading_pictures)
        self.verticalLayout_2.addWidget(self.widget_loading_data)
        self.pushButton_options = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_options.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_options.setCheckable(True)
        self.pushButton_options.setChecked(True)
        self.pushButton_options.setObjectName("pushButton_options")
        self.verticalLayout_2.addWidget(self.pushButton_options)
        self.widget_options = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_options.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_options.setObjectName("widget_options")
        self.layout_options = QtWidgets.QVBoxLayout(self.widget_options)
        self.layout_options.setContentsMargins(0, 0, 0, 20)
        self.layout_options.setObjectName("layout_options")
        self.groupBox_noise = QtWidgets.QGroupBox(self.widget_options)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_noise.sizePolicy().hasHeightForWidth())
        self.groupBox_noise.setSizePolicy(sizePolicy)
        self.groupBox_noise.setObjectName("groupBox_noise")
        self.layout_area_size_2 = QtWidgets.QVBoxLayout(self.groupBox_noise)
        self.layout_area_size_2.setContentsMargins(0, 5, 0, 9)
        self.layout_area_size_2.setSpacing(5)
        self.layout_area_size_2.setObjectName("layout_area_size_2")
        self.widget_noise = QtWidgets.QWidget(self.groupBox_noise)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_noise.sizePolicy().hasHeightForWidth())
        self.widget_noise.setSizePolicy(sizePolicy)
        self.widget_noise.setObjectName("widget_noise")
        self.layout_noise = QtWidgets.QHBoxLayout(self.widget_noise)
        self.layout_noise.setContentsMargins(-1, 0, -1, -1)
        self.layout_noise.setObjectName("layout_noise")
        self.label_text_noise = QtWidgets.QLabel(self.widget_noise)
        self.label_text_noise.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_noise.setObjectName("label_text_noise")
        self.layout_noise.addWidget(self.label_text_noise)
        self.lineEdit_noise = QtWidgets.QLineEdit(self.widget_noise)
        self.lineEdit_noise.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_noise.setObjectName("lineEdit_noise")
        self.layout_noise.addWidget(self.lineEdit_noise)
        self.pushButton_display_noise = QtWidgets.QPushButton(self.widget_noise)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_display_noise.sizePolicy().hasHeightForWidth())
        self.pushButton_display_noise.setSizePolicy(sizePolicy)
        self.pushButton_display_noise.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_display_noise.setMaximumSize(QtCore.QSize(35, 50))
        self.pushButton_display_noise.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_display_noise.setStyleSheet("QPushButton {\n"
"    /* задает иконку */\n"
"    background-image: url(:/menu/resource/update1_white_18dp.svg);\n"
"    background-position:  senter ;\n"
"\n"
"    background-repeat: no-repeat;\n"
"} \n"
"/* срабатывает, при нажатии*/\n"
"QPushButton:pressed      {\n"
"background-image: url(:/menu/resource/update2_white_18dp.svg);\n"
"}\n"
"/* срабатывает, когда пользователь наводит на элемент мышью */\n"
"QPushButton:hover {\n"
"    border: none;                                                /* без границ */\n"
"}\n"
"")
        self.pushButton_display_noise.setText("")
        self.pushButton_display_noise.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_display_noise.setObjectName("pushButton_display_noise")
        self.layout_noise.addWidget(self.pushButton_display_noise)
        self.layout_noise.setStretch(0, 2)
        self.layout_noise.setStretch(1, 1)
        self.layout_noise.setStretch(2, 1)
        self.layout_area_size_2.addWidget(self.widget_noise)
        self.layout_options.addWidget(self.groupBox_noise)
        self.groupBox_spectrum_filtration = QtWidgets.QGroupBox(self.widget_options)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_spectrum_filtration.sizePolicy().hasHeightForWidth())
        self.groupBox_spectrum_filtration.setSizePolicy(sizePolicy)
        self.groupBox_spectrum_filtration.setObjectName("groupBox_spectrum_filtration")
        self.layout_spectrum_filtration = QtWidgets.QHBoxLayout(self.groupBox_spectrum_filtration)
        self.layout_spectrum_filtration.setContentsMargins(9, 5, 9, 9)
        self.layout_spectrum_filtration.setSpacing(6)
        self.layout_spectrum_filtration.setObjectName("layout_spectrum_filtration")
        self.label_text_percent_energy = QtWidgets.QLabel(self.groupBox_spectrum_filtration)
        self.label_text_percent_energy.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_percent_energy.setObjectName("label_text_percent_energy")
        self.layout_spectrum_filtration.addWidget(self.label_text_percent_energy)
        self.lineEdit_percent_energy = QtWidgets.QLineEdit(self.groupBox_spectrum_filtration)
        self.lineEdit_percent_energy.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_percent_energy.setObjectName("lineEdit_percent_energy")
        self.layout_spectrum_filtration.addWidget(self.lineEdit_percent_energy)
        self.layout_spectrum_filtration.setStretch(0, 1)
        self.layout_spectrum_filtration.setStretch(1, 1)
        self.layout_options.addWidget(self.groupBox_spectrum_filtration)
        self.groupBox_select_axes_type = QtWidgets.QGroupBox(self.widget_options)
        self.groupBox_select_axes_type.setObjectName("groupBox_select_axes_type")
        self.layout_select_axes_type = QtWidgets.QVBoxLayout(self.groupBox_select_axes_type)
        self.layout_select_axes_type.setContentsMargins(6, 0, 0, 5)
        self.layout_select_axes_type.setSpacing(0)
        self.layout_select_axes_type.setObjectName("layout_select_axes_type")
        self.radioButton_logarithmic_axis = QtWidgets.QRadioButton(self.groupBox_select_axes_type)
        self.radioButton_logarithmic_axis.setChecked(True)
        self.radioButton_logarithmic_axis.setAutoRepeat(False)
        self.radioButton_logarithmic_axis.setAutoExclusive(True)
        self.radioButton_logarithmic_axis.setObjectName("radioButton_logarithmic_axis")
        self.layout_select_axes_type.addWidget(self.radioButton_logarithmic_axis)
        self.radioButton_linear_axis = QtWidgets.QRadioButton(self.groupBox_select_axes_type)
        self.radioButton_linear_axis.setAutoRepeat(False)
        self.radioButton_linear_axis.setAutoExclusive(True)
        self.radioButton_linear_axis.setObjectName("radioButton_linear_axis")
        self.layout_select_axes_type.addWidget(self.radioButton_linear_axis)
        self.layout_options.addWidget(self.groupBox_select_axes_type)
        self.verticalLayout_2.addWidget(self.widget_options)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.layout_menu.addWidget(self.scrollArea)
        self.widget_processing = QtWidgets.QWidget(self.widget_menu)
        self.widget_processing.setObjectName("widget_processing")
        self.layout_processing = QtWidgets.QVBoxLayout(self.widget_processing)
        self.layout_processing.setContentsMargins(0, 2, 0, 0)
        self.layout_processing.setSpacing(0)
        self.layout_processing.setObjectName("layout_processing")
        self.pushButton_start_processing = QtWidgets.QPushButton(self.widget_processing)
        self.pushButton_start_processing.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_start_processing.setObjectName("pushButton_start_processing")
        self.layout_processing.addWidget(self.pushButton_start_processing)
        self.widget_deviation_original_and_noise = QtWidgets.QWidget(self.widget_processing)
        self.widget_deviation_original_and_noise.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_deviation_original_and_noise.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_deviation_original_and_noise.setObjectName("widget_deviation_original_and_noise")
        self.layout_deviation_original_and_noise = QtWidgets.QHBoxLayout(self.widget_deviation_original_and_noise)
        self.layout_deviation_original_and_noise.setContentsMargins(-1, 0, -1, 0)
        self.layout_deviation_original_and_noise.setSpacing(0)
        self.layout_deviation_original_and_noise.setObjectName("layout_deviation_original_and_noise")
        self.label_text_deviation_original_and_noise = QtWidgets.QLabel(self.widget_deviation_original_and_noise)
        self.label_text_deviation_original_and_noise.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_text_deviation_original_and_noise.setFont(font)
        self.label_text_deviation_original_and_noise.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_deviation_original_and_noise.setObjectName("label_text_deviation_original_and_noise")
        self.layout_deviation_original_and_noise.addWidget(self.label_text_deviation_original_and_noise)
        self.label_deviation_original_and_noise = QtWidgets.QLabel(self.widget_deviation_original_and_noise)
        self.label_deviation_original_and_noise.setText("")
        self.label_deviation_original_and_noise.setAlignment(QtCore.Qt.AlignCenter)
        self.label_deviation_original_and_noise.setObjectName("label_deviation_original_and_noise")
        self.layout_deviation_original_and_noise.addWidget(self.label_deviation_original_and_noise)
        self.layout_deviation_original_and_noise.setStretch(0, 2)
        self.layout_deviation_original_and_noise.setStretch(1, 1)
        self.layout_processing.addWidget(self.widget_deviation_original_and_noise)
        self.widget_deviation_original_and_received = QtWidgets.QWidget(self.widget_processing)
        self.widget_deviation_original_and_received.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_deviation_original_and_received.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_deviation_original_and_received.setObjectName("widget_deviation_original_and_received")
        self.layout_deviation_original_and_received = QtWidgets.QHBoxLayout(self.widget_deviation_original_and_received)
        self.layout_deviation_original_and_received.setContentsMargins(-1, 0, -1, 0)
        self.layout_deviation_original_and_received.setSpacing(0)
        self.layout_deviation_original_and_received.setObjectName("layout_deviation_original_and_received")
        self.label_text_deviation_original_and_received = QtWidgets.QLabel(self.widget_deviation_original_and_received)
        self.label_text_deviation_original_and_received.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_text_deviation_original_and_received.setFont(font)
        self.label_text_deviation_original_and_received.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_deviation_original_and_received.setObjectName("label_text_deviation_original_and_received")
        self.layout_deviation_original_and_received.addWidget(self.label_text_deviation_original_and_received)
        self.label_deviation_original_and_received = QtWidgets.QLabel(self.widget_deviation_original_and_received)
        self.label_deviation_original_and_received.setText("")
        self.label_deviation_original_and_received.setAlignment(QtCore.Qt.AlignCenter)
        self.label_deviation_original_and_received.setObjectName("label_deviation_original_and_received")
        self.layout_deviation_original_and_received.addWidget(self.label_deviation_original_and_received)
        self.layout_deviation_original_and_received.setStretch(0, 2)
        self.layout_deviation_original_and_received.setStretch(1, 1)
        self.layout_processing.addWidget(self.widget_deviation_original_and_received)
        self.layout_menu.addWidget(self.widget_processing)
        self.layout_design.addWidget(self.widget_menu)
        self.widget_main = QtWidgets.QWidget(self.widget_design)
        self.widget_main.setStyleSheet("QWidget{\n"
"background-color: rgb(240, 240, 240);\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.widget_main.setObjectName("widget_main")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_main)
        self.gridLayout.setContentsMargins(9, -1, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_plot_1 = QtWidgets.QWidget(self.widget_main)
        self.widget_plot_1.setObjectName("widget_plot_1")
        self.layout_plot_1 = QtWidgets.QVBoxLayout(self.widget_plot_1)
        self.layout_plot_1.setContentsMargins(0, 0, 0, 0)
        self.layout_plot_1.setSpacing(0)
        self.layout_plot_1.setObjectName("layout_plot_1")
        self.gridLayout.addWidget(self.widget_plot_1, 0, 0, 1, 1)
        self.widget_plot_2 = QtWidgets.QWidget(self.widget_main)
        self.widget_plot_2.setObjectName("widget_plot_2")
        self.layout_plot_2 = QtWidgets.QVBoxLayout(self.widget_plot_2)
        self.layout_plot_2.setContentsMargins(0, 0, 0, 0)
        self.layout_plot_2.setSpacing(0)
        self.layout_plot_2.setObjectName("layout_plot_2")
        self.gridLayout.addWidget(self.widget_plot_2, 0, 1, 1, 1)
        self.widget_plot_3 = QtWidgets.QWidget(self.widget_main)
        self.widget_plot_3.setObjectName("widget_plot_3")
        self.layout_plot_3 = QtWidgets.QVBoxLayout(self.widget_plot_3)
        self.layout_plot_3.setContentsMargins(0, 0, 0, 0)
        self.layout_plot_3.setSpacing(0)
        self.layout_plot_3.setObjectName("layout_plot_3")
        self.gridLayout.addWidget(self.widget_plot_3, 1, 0, 1, 1)
        self.widget_plot_4 = QtWidgets.QWidget(self.widget_main)
        self.widget_plot_4.setObjectName("widget_plot_4")
        self.layout_plot_4 = QtWidgets.QVBoxLayout(self.widget_plot_4)
        self.layout_plot_4.setContentsMargins(0, 0, 0, 0)
        self.layout_plot_4.setSpacing(0)
        self.layout_plot_4.setObjectName("layout_plot_4")
        self.gridLayout.addWidget(self.widget_plot_4, 1, 1, 1, 1)
        self.layout_design.addWidget(self.widget_main)
        self.horizontalLayout.addWidget(self.widget_design)

        self.retranslateUi(Dialog)
        self.radioButton_loading_pictures.toggled['bool'].connect(self.widget_loading_pictures.setVisible) # type: ignore
        self.radioButton_loading_pictures.toggled['bool'].connect(self.widget_loading_pictures.setEnabled) # type: ignore
        self.pushButton_options.clicked['bool'].connect(self.widget_options.setVisible) # type: ignore
        self.pushButton_loading_data.clicked['bool'].connect(self.widget_loading_data.setVisible) # type: ignore
        self.radioButton_generation_domes.toggled['bool'].connect(self.widget_dome_parameters.setVisible) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Фильтрация изображения"))
        self.pushButton_loading_data.setText(_translate("Dialog", "Данные"))
        self.groupBox_choice_dome_or_picture.setTitle(_translate("Dialog", "Выбор исходных данных"))
        self.radioButton_generation_domes.setText(_translate("Dialog", "Генерация куполов"))
        self.radioButton_loading_pictures.setText(_translate("Dialog", "Загрузка картинки"))
        self.groupBox_area_size.setTitle(_translate("Dialog", "Размер области"))
        self.label_text_width_area.setText(_translate("Dialog", "Ширина"))
        self.lineEdit_width_area.setText(_translate("Dialog", "256"))
        self.label_text_height_area.setText(_translate("Dialog", "Высота"))
        self.lineEdit_height_area.setText(_translate("Dialog", "128"))
        self.groupBox_dome_1.setTitle(_translate("Dialog", "Купол №1"))
        self.label_text_amplitude_1.setText(_translate("Dialog", "Амплитуда"))
        self.lineEdit_amplitude_1.setText(_translate("Dialog", "5"))
        self.label_text_x0_1.setText(_translate("Dialog", "x0"))
        self.lineEdit_x0_1.setText(_translate("Dialog", "200"))
        self.label_text_sigma_x_1.setText(_translate("Dialog", "σ_x"))
        self.lineEdit_sigma_x_1.setText(_translate("Dialog", "2"))
        self.label_text_y0_1.setText(_translate("Dialog", "y0"))
        self.lineEdit_y0_1.setText(_translate("Dialog", "50"))
        self.label_text_sigma_y_1.setText(_translate("Dialog", "σ_y"))
        self.lineEdit_sigma_y_1.setText(_translate("Dialog", "2"))
        self.groupBox_dome_2.setTitle(_translate("Dialog", "Купол №2"))
        self.label_text_amplitude_2.setText(_translate("Dialog", "Амплитуда"))
        self.lineEdit_amplitude_2.setText(_translate("Dialog", "5"))
        self.label_text_x0_2.setText(_translate("Dialog", "x0"))
        self.lineEdit_x0_2.setText(_translate("Dialog", "220"))
        self.label_text_sigma_x_2.setText(_translate("Dialog", "σ_x"))
        self.lineEdit_sigma_x_2.setText(_translate("Dialog", "2"))
        self.label_text_y0_2.setText(_translate("Dialog", "y0"))
        self.lineEdit_y0_2.setText(_translate("Dialog", "50"))
        self.label_text_sigma_y_2.setText(_translate("Dialog", "σ_y"))
        self.lineEdit_sigma_y_2.setText(_translate("Dialog", "2"))
        self.groupBox_dome_3.setTitle(_translate("Dialog", "Купол №3"))
        self.label_text_amplitude_3.setText(_translate("Dialog", "Амплитуда"))
        self.lineEdit_amplitude_3.setText(_translate("Dialog", "0"))
        self.label_text_x0_3.setText(_translate("Dialog", "x0"))
        self.lineEdit_x0_3.setText(_translate("Dialog", "400"))
        self.label_text_sigma_x_3.setText(_translate("Dialog", "σ_x"))
        self.lineEdit_sigma_x_3.setText(_translate("Dialog", "120"))
        self.label_text_y0_3.setText(_translate("Dialog", "y0"))
        self.lineEdit_y0_3.setText(_translate("Dialog", "120"))
        self.label_text_sigma_y_3.setText(_translate("Dialog", "σ_y"))
        self.lineEdit_sigma_y_3.setText(_translate("Dialog", "100"))
        self.pushButton_display_domes.setText(_translate("Dialog", "Расчитать"))
        self.label_text_loading_pictures.setText(_translate("Dialog", "Загрузка файла"))
        self.groupBox_picture_type.setTitle(_translate("Dialog", "Вид отображения"))
        self.radioButton_color_picture.setText(_translate("Dialog", "Цветная"))
        self.radioButton_gray_picture.setText(_translate("Dialog", "Серая"))
        self.pushButton_options.setText(_translate("Dialog", "Параметры"))
        self.groupBox_noise.setTitle(_translate("Dialog", "Шум"))
        self.label_text_noise.setText(_translate("Dialog", "Шум %"))
        self.lineEdit_noise.setText(_translate("Dialog", "40"))
        self.groupBox_spectrum_filtration.setTitle(_translate("Dialog", "Фильтрация спектра"))
        self.label_text_percent_energy.setText(_translate("Dialog", "Энергии %"))
        self.lineEdit_percent_energy.setText(_translate("Dialog", "70"))
        self.groupBox_select_axes_type.setTitle(_translate("Dialog", "Выбор типа оси спектра"))
        self.radioButton_logarithmic_axis.setText(_translate("Dialog", "Логарифмические оси"))
        self.radioButton_linear_axis.setText(_translate("Dialog", "Линейные оси"))
        self.pushButton_start_processing.setText(_translate("Dialog", "Обработка"))
        self.label_text_deviation_original_and_noise.setText(_translate("Dialog", "ℰ_org_noise"))
        self.label_text_deviation_original_and_received.setText(_translate("Dialog", "ℰ_org_received"))
import res_rc
